spring:
  mvc:
    static-path-patterns: /**
  resources:
    static-locations: classpath:/static
  profiles:
    active: dev
  application:
    name: Worldwide Windsurfers Weather Service
server:
  servlet:
    context-path: /api/
  port: ${PORT:8080}

